import type { FastifyPluginAsyncZod } from 'fastify-type-provider-zod'
import { z } from 'zod'
import { getUser } from '../../functions/get-user'
import { UserNotFoundError } from '../../errors/errors'

export const getUserRoute: FastifyPluginAsyncZod = async app => {
  app.get(
    '/users/:id',
    {
      schema: {
        tags: ['users'],
        summary: 'Busca um usu치rio',
        description: 'Endpoint para buscar um usu치rio pelo ID.',
        params: z.object({
          id: z.string().describe('ID do usu치rio'),
        }),
        response: {
          200: z
            .object({
              id: z.number().int().positive().describe('ID do usu치rio'),
              name: z.string().describe('Nome do usu치rio'),
              email: z.string().email().describe('E-mail do usu치rio'),
              created_at: z.string().describe('Data de cria칞칚o do usu치rio'),
            })
            .describe('Usu치rio encontrado'),
          404: z
            .object({ error: z.string() })
            .describe('Usu치rio n칚o encontrado'),
          500: z.object({ error: z.string() }).describe('Erro interno'),
        },
      },
    },
    async (request, reply) => {
      try {
        const { id } = request.params

        const userId = Number(id)
        if (Number.isNaN(userId) || userId <= 0) {
          return reply.status(400).send({ error: 'ID inv치lido' })
        }

        const user = await getUser({ id: userId })

        return reply.status(200).send(user)
      } catch (error) {
        if (error instanceof UserNotFoundError) {
          console.error('游댠 Usu치rio n칚o encontrado:', error)
          return reply.status(404).send({ error: 'Usu치rio n칚o encontrado' })
        }
        console.error('游댠 Erro ao buscar usu치rio:', error)
        return reply.status(500).send({ error: 'Erro ao buscar usu치rio' })
      }
    }
  )
}
